Repository e2b-dev/dashboard, pull requests merged in 2025-05, with the labels that each got.

#54 Improve ux for default "email" team names
  src/configs/keys.ts
  src/features/dashboard/sandboxes/stores/table-store.ts
  src/features/dashboard/sidebar/menu.tsx
  src/features/dashboard/team/name-card.tsx
  src/features/dashboard/team/profile-picture-card.tsx
  src/lib/hooks/use-server-context.tsx
  src/server/team/get-team.ts
  src/server/team/types.ts
  src/types/actions.d.ts
  src/types/dashboard.d.ts
  src/types/dashboard.types.ts
  src/ui/polling-button.tsx
  src/ui/primitives/avatar.tsx
Labels: enhancement

#56 Call billing api to redirect to stripe billing portal
  .env.example
  scripts/check-app-env.ts
  src/features/dashboard/billing/customer-portal-link.tsx
  src/lib/env.ts
  src/server/billing/billing-actions.ts
  src/server/billing/get-billing-limits.ts
  src/types/billing.d.ts
Labels: feature

#57 Fix client side sandbox id construction
  src/features/dashboard/sandboxes/table-config.tsx
Labels: bug

#60 Use billing endpoint for agg usage
  .env.example
  .github/workflows/test.yml
  README.md
  bun.lock
  package.json
  src/features/dashboard/sidebar/menu.tsx
  src/features/dashboard/usage/chart-config.tsx
  src/features/dashboard/usage/cost-card.tsx
  src/features/dashboard/usage/cost-chart.tsx
  src/features/dashboard/usage/ram-card.tsx
  src/features/dashboard/usage/ram-chart.tsx
  src/features/dashboard/usage/sandboxes-card.tsx
  src/features/dashboard/usage/sandboxes-chart.tsx
  src/features/dashboard/usage/vcpu-card.tsx
  src/features/dashboard/usage/vcpu-chart.tsx
  src/lib/clients/pg.ts
  src/lib/env.ts
  src/server/usage/get-sandboxes-started.ts
  src/server/usage/get-usage.ts
  src/server/usage/types.ts
  src/types/billing.d.ts
Labels: enhancement

#62 Improve usage page prose
  src/features/dashboard/usage/cost-card.tsx
  src/features/dashboard/usage/ram-card.tsx
  src/features/dashboard/usage/sandboxes-card.tsx
  src/features/dashboard/usage/sandboxes-chart.tsx
  src/features/dashboard/usage/vcpu-card.tsx
Labels: enhancement

#64 Improve auth callback logging
  src/app/api/auth/callback/route.ts
  src/lib/clients/logger.ts
Labels: enhancement

#65 Prepare cli auth & access token retrieval for api key hashing
  src/app/(auth)/auth/cli/page.tsx
  src/app/api/team/state/route.ts
  src/features/dashboard/account/user-access-token.tsx
  src/features/dashboard/sidebar/menu.tsx
  src/lib/utils/server.ts
  src/server/auth/get-default-team.ts
  src/server/user/user-actions.ts
  src/types/api.d.ts
Labels: enhancement

#66 Update tiers benefits items according to landing page
  src/configs/tiers.tsx
Labels: documentation

#67 Fix pro tier indication for custom tiers
  src/features/dashboard/billing/tier-card.tsx
Labels: bug, improvement

#69 Improve Sentry initialization
  .env.example
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/lib/env.ts
Labels: improvement
