Repository e2b-dev/dashboard, pull requests merged in 2025-07, with the labels that each got.

#88 Make "API Key" label consistent in errors and API responses
  src/features/dashboard/keys/create-api-key-dialog.tsx
  src/features/dashboard/keys/table-row.tsx
  src/server/keys/key-actions.ts
Labels: improvement

#92 Fix: Fix redirecting to the correct Supabase PKCE flow for external origin requests
  src/app/api/auth/confirm/route.ts
Labels: bug

#93 Remove: confirmation_url schema validation
  src/app/api/auth/confirm/route.ts
Labels: bug

#96 Feat: Show sandbox metrics in sandboxes table
  .gitignore
  bun.lock
  package.json
  spec/openapi.yaml
  src/__test__/README.md
  src/__test__/development/metrics.test.ts
  src/app/api/teams/[teamId]/sandboxes/metrics/route.ts
  src/app/api/teams/[teamId]/sandboxes/metrics/types.ts
  src/app/dashboard/[teamIdOrSlug]/sandboxes/page.tsx
  src/configs/intervals.ts
  src/configs/mock-data.ts
  src/features/dashboard/sandboxes/header.tsx
  src/features/dashboard/sandboxes/hooks/use-sandboxes-metrics.tsx
  src/features/dashboard/sandboxes/stores/table-store.ts
  src/features/dashboard/sandboxes/table-body.tsx
  src/features/dashboard/sandboxes/table-cells.tsx
  src/features/dashboard/sandboxes/table-config.tsx
  src/features/dashboard/sandboxes/table-filters.tsx
  src/features/dashboard/sandboxes/table-header.tsx
  src/features/dashboard/sandboxes/table-row.tsx
  src/features/dashboard/sandboxes/table.tsx
  src/features/dashboard/templates/by-e2b-badge.tsx
  src/features/dashboard/templates/table-body.tsx
  src/features/dashboard/templates/table-cells.tsx
  src/features/dashboard/templates/table-config.tsx
  src/features/dashboard/templates/table.tsx
  src/lib/clients/api.ts
  src/lib/utils/sandboxes.ts
  src/server/sandboxes/get-team-sandboxes-metrics.ts
  src/server/sandboxes/get-team-sandboxes.ts
  src/types/api.d.ts
  src/types/infra-api.d.ts
  src/types/sandboxes.types.ts
  src/ui/data-table.tsx
Labels: feature, improvement

#99 Fix: Disable Sandboxes metrics sorting + Improve: Metrics state management
  .env.example
  bun.lock
  package.json
  src/__test__/development/metrics.test.ts
  src/app/layout.client.tsx
  src/features/dashboard/sandboxes/hooks/use-sandboxes-metrics.tsx
  src/features/dashboard/sandboxes/stores/metrics-store.ts
  src/features/dashboard/sandboxes/stores/table-store.ts
  src/features/dashboard/sandboxes/table-cells.tsx
  src/features/dashboard/sandboxes/table-config.tsx
  src/features/dashboard/sandboxes/table.tsx
  src/lib/utils/sandboxes.ts
Labels: bug

#103 Patch: Downgrade Next.js version
  bun.lock
  package.json
Labels: bug

#104 Feat: Add Campaigns redirects + Expose new proxy route
  next.config.mjs
  src/configs/rewrites.ts
  vercel.json
Labels: feature

#105 Chore: Update Campaign redirects for enhanced tracking
  next.config.mjs
Labels: chore

#78 Feat: Application layer for sandbox details/inspect view
  .env.example
  .eslintignore
  .github/workflows/test.yml
  bun.lock
  next.config.mjs
  package.json
  source.config.ts
  spec/envd/buf.gen.yaml
  spec/envd/filesystem/filesystem.proto
  src/app/_docs/[[...slug]]/page.tsx
  src/app/_docs/layout.tsx
  src/app/_docs/not-found.tsx
  src/app/dashboard/layout.tsx
  src/configs/fumadocs.ts
  src/configs/metadata.ts
  src/content/docs/(documentation)/code-interpreting/analyze-data-with-ai/index.mdx
  src/content/docs/(documentation)/code-interpreting/analyze-data-with-ai/meta.json
  src/content/docs/(documentation)/code-interpreting/analyze-data-with-ai/pre-installed-libraries.mdx
  src/content/docs/(documentation)/code-interpreting/create-charts-visualizations/index.mdx
  src/content/docs/(documentation)/code-interpreting/create-charts-visualizations/interactive-charts.mdx
  src/content/docs/(documentation)/code-interpreting/create-charts-visualizations/meta.json
  src/content/docs/(documentation)/code-interpreting/create-charts-visualizations/static-charts.mdx
  src/content/docs/(documentation)/code-interpreting/supported-languages/meta.json
  src/content/docs/(documentation)/index.mdx
  src/content/docs/(documentation)/meta.json
  src/content/docs/(documentation)/quickstart/connect-llms.mdx
  src/content/docs/(documentation)/quickstart/index.mdx
  src/content/docs/(documentation)/quickstart/install-custom-packages.mdx
  src/content/docs/(documentation)/quickstart/meta.json
  src/content/docs/(documentation)/quickstart/migrating-from-v0.mdx
  src/content/docs/(documentation)/quickstart/upload-download-files.mdx
  src/features/client-providers.tsx
  src/features/dashboard/sandbox/context.tsx
  src/features/dashboard/sandbox/inspect/context.tsx
  src/features/dashboard/sandbox/inspect/filesystem/store.ts
  src/features/dashboard/sandbox/inspect/filesystem/types.ts
  src/features/dashboard/sandbox/inspect/hooks/use-content.ts
  src/features/dashboard/sandbox/inspect/hooks/use-directory.ts
  src/features/dashboard/sandbox/inspect/hooks/use-file.tsx
  src/features/dashboard/sandbox/inspect/hooks/use-node.ts
  src/features/dashboard/sandbox/inspect/sandbox-manager.ts
  src/features/dashboard/sandboxes/table-cells.tsx
  src/features/dashboard/server-context.tsx
  src/lib/clients/api.ts
  src/lib/clients/envd/filesystem/filesystem_connect.ts
  src/lib/clients/envd/filesystem/filesystem_pb.ts
  src/lib/env.ts
  src/lib/hooks/use-teams.ts
  src/lib/hooks/use-user.ts
  src/lib/source.ts
  src/lib/utils/filesystem.ts
  src/server/sandboxes/get-sandbox-root.ts
  src/types/api.d.ts
  tsconfig.json
Labels: feature

#108 Chore: Update minimum ENVD version for Sandbox Inspect to 0.2.9
  src/configs/versioning.ts
Labels: chore

#109 Fix: serverExternalPackages for correct loki transport
  next.config.mjs
Labels: bug
